# Generated by Django 4.0 on 2022-02-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mycertificatespic',
            new_name='databasesection',
        ),
    ]
