# Generated by Django 4.0 on 2022-02-14 15:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0005_coursedetails_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
