# Generated by Django 4.0 on 2022-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0006_coursedetails_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='content',
            new_name='sub1',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='created',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='sub2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='sub3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='sub4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
