# Generated by Django 4.0 on 2022-02-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0007_rename_content_coursedetails_sub1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coursedetails',
        ),
    ]
