# Generated by Django 4.0 on 2022-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0008_delete_coursedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasesection',
            old_name='section',
            new_name='modulecode',
        ),
        migrations.AddField(
            model_name='databasesection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databasesection',
            name='details',
            field=models.CharField(blank=True, max_length=955, null=True),
        ),
        migrations.AddField(
            model_name='databasesection',
            name='modulename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
