# Generated by Django 4.0 on 2022-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseproject', '0010_delete_databasesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='modulesdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulecode', models.CharField(blank=True, max_length=255, null=True)),
                ('modulename', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=955, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
