# Generated by Django 4.0 on 2022-02-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postassignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulename', models.CharField(blank=True, max_length=255, null=True)),
                ('releasedate', models.DateTimeField()),
                ('duedate', models.DateTimeField()),
                ('question', models.CharField(blank=True, max_length=955, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/Assignmentque')),
                ('message', models.CharField(blank=True, max_length=955, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modulecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseproject.modulesdetails')),
            ],
        ),
    ]
