# Generated by Django 4.0 on 2022-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0013_alter_postassignments_modulecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignments',
            name='modulename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
