# Generated by Django 4.0 on 2022-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0014_alter_postassignments_modulename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
