# Generated by Django 4.0 on 2022-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0017_teacherfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfeedback',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
