# Generated by Django 4.0 on 2022-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0018_teacherfeedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/Assignmentque')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('submittedon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
