# Generated by Django 4.0 on 2022-02-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0020_alter_uploadassignment_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadassignment',
            new_name='uploadassignments',
        ),
    ]
