# Generated by Django 4.0 on 2022-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0021_rename_uploadassignment_uploadassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadassignments',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
