# Generated by Django 4.0 on 2022-02-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseproject', '0023_studentmsg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherfeedback',
            old_name='subject',
            new_name='To',
        ),
    ]
